---
- name: install KVM dependencies
  apt:
    name: "{{ kvm_dependencies }}"
    state: present

- name: install virt manager GUI
  apt:
    name: virt-manager
    state: present
  when: kvm_gui|bool

- name: "download docker_kvm2_driver"
  get_url:
      url: "{{ docker_kvm2_driver_url }}"
      dest: "{{ docker_kvm2_driver_binary }}"
      mode: 0755
      force: no
  when: docker_kvm2_driver|bool
